# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aad5797b72fd993775332bca85d692fd0afa895f6f314e8747983ed5cf1e3d2ce29958dd29224f9f972eeaf94ec861c7ffa3e1a7532f375759484e8bcda6a44

test:
  secret_key_base: 680131e449978d8c5d4c1ba63b33da3cea678dd891c51a867863e0f713262edd46145c7e095a3904760ba2adeda1b16984f7df4b5351918fe06c4c78d6127ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
